# -*- coding: utf-8 -*-
"""practica 2 deteccion de personas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKCkOL37P5M1ZYVIXmXLZDfDFidNcZRU

ejemplo para detectar personas y marcalas en la imagen
usando mobileNet based sigle shot multibox(SSD)
"""

#importar las librerias
import cv2
import matplotlib.pyplot as plt

#mount the Google Drive to access the model and images
from google.colab import drive
drive.mount('/content/drive')

#subir manualmente el modelo preentrenado en la ruta (/conten/drive/MyDrive/Recursos/ssd_mobileNet)
#ruta de los archivos
rutaModelo="/content/drive/MyDrive/Recursos/ssd_mobileNet/frozen_inference_graph.pb"
rutaConfiguracion="/content/drive/MyDrive/Recursos/ssd_mobileNet/ssd_mobilenet_v2_coco_2018_03_29.pbtxt"
rutaClases="/content/drive/MyDrive/Recursos/ssd_mobileNet/object_detection_classes_coco.txt"
tamaño_imagen=300
#cargar el modelo de la red neuronal
modelo=cv2.dnn.readNetFromTensorflow(rutaModelo,rutaConfiguracion)



#funcion para rotular el texto
def rotular_texto(imagen,texto,x,y,color):
  FONTFACE=cv2.FONT_HERSHEY_SIMPLEX
  FONT_SCALE=0.5
  THICKNESS=1
  ColorTexto=(0,0,0)
  if(color==1):
    colorLinea=(0,255,0)
  elif(color==2):
      colorLinea=(255,100,0)
      colorTexto=(255,255,255)
  else:
    colorLinea=(0,0,255)
  textSize=cv2.getTextSize(texto,FONTFACE,FONT_SCALE,THICKNESS)
  dim=textSize[0]
  baseline=textSize[1]
  cv2.rectangle(imagen,(x,y-dim[1]-baseline),(x+dim[0],y+baseline),colorLinea,cv2.FILLED);
  cv2.putText(imagen,texto,(x,y-5),FONTFACE,FONT_SCALE,colorTexto,THICKNESS,cv2.LINE_AA)

#Funcion para detectar objetos
def detectar_Objetos(modelo,imagen):
  blob=cv2.dnn.blobFromImage(imagen, 1.0, size=(tamaño_imagen,tamaño_imagen),mean=(0,0,0),swapRB=True,crop=False)
  modelo.setInput(blob)
  objetos=modelo.forward()
  return objetos

#funcion actualizada para detectar y marcalos
def detectar_Objetos_clase(nclaseDetectar,nombreClaseDetectar,umbralClasificacion,modelo,imagenRGB,colorLinea,tamañoLinea):
  blob=cv2.dnn.blobFromImage(imagenRGB, 1.0, size=(tamaño_imagen,tamaño_imagen),mean=(0,0,0),swapRB=True,crop=False)
  modelo.setInput(blob)
  listaObjetos=modelo.forward()
  totalDetecciones=listaObjetos.shape[2]
  print("total de objetosDetectados: ",totalDetecciones)
  filasImagen=imagenRGB.shape[0]
  columnasImagen=imagenRGB.shape[1]
  for i in range(totalDetecciones):
    clase=int(listaObjetos[0,0,i,1])
    score=float(listaObjetos[0,0,i,2])
    if(score>=umbralClasificacion and clase==nclaseDetectar):
      print("clase %d=%s score=%1.1f"%(clase,nombreClaseDetectar,score*100))
      x=int(listaObjetos[0,0,i,3]*columnasImagen)
      y=int(listaObjetos[0,0,i,4]*filasImagen)
      ancho=int(listaObjetos[0,0,i,5]*columnasImagen-x)
      alto=int(listaObjetos[0,0,i,6]*filasImagen-y)
      cv2.rectangle(imagenRGB,(x,y),(x+ancho,y+alto),colorLinea,tamañoLinea)
      texto="%1.1f : %s"%(score*100,nombreClaseDetectar)
      rotular_texto(imagenRGB,texto,x,y,2)
  imagenRGB=cv2.cvtColor(imagenRGB,cv2.COLOR_BGR2RGB)
  return (nombreClaseDetectar,imagenRGB)

import cv2
import matplotlib.pyplot as plt

#subir manualmente el modelo preentrenado en la ruta (/conten/drive/MyDrive/Recursos/ssd_mobileNet)
#ruta de los archivos
rutaModelo="/content/drive/MyDrive/Recursos/ssd_mobileNet/frozen_inference_graph.pb"
rutaConfiguracion="/content/drive/MyDrive/Recursos/ssd_mobileNet/ssd_mobilenet_v2_coco_2018_03_29.pbtxt"
rutaClases="/content/drive/MyDrive/Recursos/ssd_mobileNet/object_detection_classes_coco.txt"
tamaño_imagen=300
#cargar el modelo de la red neuronal
modelo=cv2.dnn.readNetFromTensorflow(rutaModelo,rutaConfiguracion)

#funcion para rotular el texto
def rotular_texto(imagen,texto,x,y,color):
  FONTFACE=cv2.FONT_HERSHEY_SIMPLEX
  FONT_SCALE=0.5
  THICKNESS=1
  ColorTexto=(0,0,0)
  if(color==1):
    colorLinea=(0,255,0)
  elif(color==2):
      colorLinea=(255,100,0)
      ColorTexto=(255,255,255) # Corrected variable name
  else:
    colorLinea=(0,0,255)
  # Correctly unpack the return values of cv2.getTextSize
  # textSize is (width, height) tuple, and actual_baseline is the baseline value
  textSize, actual_baseline = cv2.getTextSize(texto,FONTFACE,FONT_SCALE,THICKNESS)
  dim = textSize # dim is now (width, height)
  # Use dim[1] for height and dim[0] for width, and actual_baseline for the baseline
  cv2.rectangle(imagen,(x,y-dim[1]-actual_baseline),(x+dim[0],y+actual_baseline),colorLinea,cv2.FILLED);
  cv2.putText(imagen,texto,(x,y-5),FONTFACE,FONT_SCALE,ColorTexto,THICKNESS,cv2.LINE_AA)


#funcion actualizada para detectar y marcalos
def detectar_Objetos_clase(nclaseDetectar,nombreClaseDetectar,umbralClasificacion,modelo,imagenRGB,colorLinea,tamañoLinea):
  blob=cv2.dnn.blobFromImage(imagenRGB, 1.0, size=(tamaño_imagen,tamaño_imagen),mean=(0,0,0),swapRB=True,crop=False)
  modelo.setInput(blob)
  listaObjetos=modelo.forward()
  totalDetecciones=listaObjetos.shape[2]
  print("total de objetosDetectados: ",totalDetecciones)
  filasImagen=imagenRGB.shape[0]
  columnasImagen=imagenRGB.shape[1]
  for i in range(totalDetecciones):
    clase=int(listaObjetos[0,0,i,1])
    score=float(listaObjetos[0,0,i,2])
    if(score>=umbralClasificacion and clase==nclaseDetectar):
      print("clase %d=%s score=%1.1f"%(clase,nombreClaseDetectar,score*100))
      x=int(listaObjetos[0,0,i,3]*columnasImagen)
      y=int(listaObjetos[0,0,i,4]*filasImagen)
      ancho=int(listaObjetos[0,0,i,5]*columnasImagen-x)
      alto=int(listaObjetos[0,0,i,6]*filasImagen-y)
      cv2.rectangle(imagenRGB,(x,y),(x+ancho,y+alto),colorLinea,tamañoLinea)
      texto="%1.1f : %s"%(score*100,nombreClaseDetectar)
      rotular_texto(imagenRGB,texto,x,y,2)
  imagenRGB=cv2.cvtColor(imagenRGB,cv2.COLOR_BGR2RGB)
  return (nombreClaseDetectar,imagenRGB)

#clasificar una imagen y detectar el objetos
rutaImagen="/content/drive/MyDrive/Recursos/Imagenes/personaT.JPG"
img=cv2.imread(rutaImagen)

# Check if the image was loaded successfully
if img is None:
    print(f"Error: No se pudo cargar la imagen desde la ruta: {rutaImagen}")
    print("Por favor, verifica que la ruta es correcta y que el archivo existe.")
else:
    umbral=0.7
    tamañoLinea=3
    colorLinea=(255,255,0) # Changed color to Cyan (B,G,R)
    (nombreClase,imagenRGB)=detectar_Objetos_clase(1,"persona",umbral,modelo,img,colorLinea,tamañoLinea)
    plt.figure(figsize=(30,1))
    plt.imshow(imagenRGB)
    plt.show()

